Fix libusb-1.0.22 deprecated libusb_set_debug
Since libusb-1.0.22, libusb_set_debug is deprecated and replaced with
libusb_set_option.

Details:
https://github.com/libusb/libusb/commit/539f22e2fd916558d11ab9a66f10f461c5593168

Compiling error:
usbredirhost.c: In function ‘usbredirhost_open_full’:
usbredirhost.c:753:5: error: ‘libusb_set_debug’ is deprecated: Use
libusb_set_option instead [-Werror=deprecated-declarations]
     libusb_set_debug(host->ctx, host->verbose);
     ^~~~~~~~~~~~~~~~

Signed-off-by: Han Han <hhan@redhat.com>
Acked-by: Jonathon Jongsma <jjongsma@redhat.com>